/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as ChatsConversationIdRouteImport } from './routes/chats.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/chats/$conversationId',
  path: '/chats/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calls' | '/chats/$conversationId' | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calls' | '/chats/$conversationId' | '/chats'
  id: '__root__' | '/' | '/calls' | '/chats/$conversationId' | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$conversationId': {
      id: '/chats/$conversationId'
      path: '/chats/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
